### ISSUE TITLE
problem extracting .zip on windows

### ISSUE THREAD

**Issue by katmratliff** [UNCG-DAISY/psi-collect#103] opened 2020-02-20 22:04 UTC
**Describe the bug**
I get the `AttributeError` message `'ZipInfo' object has no attribute 'name'` when extracting .zip archives on my windows machine. This happens when downloading/extracting to the default directory or to a directory of my choice (e.g., on the desktop). Interestingly, the files do still seem to extract, but if you are trying to download and extract multiple archive files, this breaks the process so that only the first one gets downloaded and extracted.

**Screenshots**
![image](https://user-images.githubusercontent.com/12630578/74982620-73f00900-5402-11ea-902f-67d99df6d775.png)

**Additional context**
It is very possible that this is an issue with my network/machine (federal government). I suspect this is the case if other windows users/reviewers haven't had this issue. I have no trouble downloading/extracting .tar archives.

Note: Submitting this issue as part of the JOSS review process (openjournals/joss-reviews#2075)

**Comment by conlin-matt** [comment] 2020-02-20 22:35
@katmratliff I did not have any issues when I tested this on both MacOS and Windows (though I only tested for Hurricane Sandy...)

**Comment by Matmorcat** [comment] 2020-02-20 22:39
I was able to reproduce her issue with that specific archive, though the others I've tested work. 

Thanks for catching this, @katmratliff !

EDIT: The issue is fixed by PR #105

**Closed as completed** 2020-02-20 22:57 UTC
Labels: bug
